# Generated by Django 5.0.6 on 2025-05-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='merchant_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('hand-made', 'Hand-Made'), ('grocery', 'Grocery')], default='restaurant', max_length=100),
        ),
    ]
