# Generated by Django 5.0.6 on 2025-04-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_slideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/restaurants/covers'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to='images/restaurants/images'),
        ),
    ]
