# Generated by Django 5.0.6 on 2025-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
