# Generated by Django 5.0.6 on 2025-05-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_menucategory_name_en_alter_menuitem_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.menucategory'),
        ),
    ]
