# Generated by Django 5.0.6 on 2025-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(blank=True, default='unset', max_length=255, null=True)),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourites', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
