# Generated by Django 5.0.6 on 2025-04-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, default='unset', max_length=255, null=True),
        ),
    ]
