# Generated by Django 5.0.6 on 2025-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_password'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='client',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to='restaurants.restaurant'),
        ),
    ]
