# Generated by Django 5.0.6 on 2025-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_birth_date_remove_client_is_blocked_and_more'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='restaurants.restaurant'),
        ),
    ]
